name: cagong_googlemap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+5

environment:
  sdk: '>=3.4.4 <4.0.0'

#expandable bottomsheet
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  image: ^4.0.15
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  http: ^1.4.0
  flutter_svg: ^2.0.10
  logging: ^1.3.0
  webview_flutter: ^4.4.2
  tosspayments_widget_sdk_flutter: ^2.1.2
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  csv: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/coupons/
    - assets/json/cafe_info.json
    - assets/images/special.png
    - assets/images/marker.png
    - assets/images/current_location_marker.png
    - assets/json/cafe_info.json 
    - assets/images/
    - web/assets/

  fonts:
  - family: Pretendard
    fonts:
      - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
      - asset: assets/fonts/Pretendard/Pretendard-Thin.otf
        weight: 100
      - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.otf
        weight: 200        
      - asset: assets/fonts/Pretendard/Pretendard-Light.otf
        weight: 300
      - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
        weight: 500
      - asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
        weight: 600
      - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
        weight: 700
      - asset: assets/fonts/Pretendard/Pretendard-ExtraBold.otf
        weight: 800
      - asset: assets/fonts/Pretendard/Pretendard-Black.otf
        weight: 900
